### ISSUE TITLE
YouTube video sticks to cursor when placing in a room

### ISSUE THREAD

**Issue by SpaceBeing1** [gomegaminds/hubs#185] opened 2023-01-18 18:46 UTC
This is an interesting bug... when I place a YouTube video in a classroom using  the Classroom Editor, it sticks to the cursor and I am unable to move or position it.  The only way to resolve it is to move it far enough away from me that it converts back to the YouTube logo.  Then I am able to place it as usual.

![Screenshot 2023-01-18 134649](https://user-images.githubusercontent.com/111762850/213267935-66214712-50d5-4c52-b427-7ce5bc7d4a18.jpg)

**Comment by edvardodegaard** [comment] 2023-01-19 02:43
This is not a bug but the way CSS2D rendering works. The video you see is a real youtube video embedded on the page, and you cannot drag it as you are just triggering the youtube controls inside the window using the cursor. The reason why we have the youtube logo is so that you can position it.

**Comment by edvardodegaard** [comment] 2023-01-28 13:02
Closing this, it is intended behaviour, not a bug. Follow up when CSS3D implementation is done.

**Closed as completed by edvardodegaard** 2023-01-28 13:02 UTC
Labels: bug
